version: '3'
services:
  php:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: tivaa
    container_name: tivaa-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - tivaa-network

  nginx:
    image: nginx:alpine
    container_name: tivaa-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "81:80"
      - "444:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - tivaa-network

  db:
    image: mysql:5.7.22
    container_name: tivaa-db
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: tivaa_jewelry
      MYSQL_ROOT_PASSWORD: quangha2611
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./docker/mysql/mysql.conf:/etc/mysql/mysql.conf
    networks:
      - tivaa-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: tivaa-pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
    networks:
      - tivaa-network

networks:
  tivaa-network:
    driver: bridge

volumes:
  dbdata:
    driver: local